#ifndef _INCLUDED_feedforward_group_variable_set_conditional_codeobject_1
#define _INCLUDED_feedforward_group_variable_set_conditional_codeobject_1

#include "objects.h"

void _run_feedforward_group_variable_set_conditional_codeobject_1();


#endif
