#ifndef _INCLUDED_feedforward_group_variable_set_conditional_codeobject
#define _INCLUDED_feedforward_group_variable_set_conditional_codeobject

#include "objects.h"

void _run_feedforward_group_variable_set_conditional_codeobject();


#endif
