#ifndef _INCLUDED_neurongroup_group_variable_set_conditional_codeobject
#define _INCLUDED_neurongroup_group_variable_set_conditional_codeobject

#include "objects.h"

void _run_neurongroup_group_variable_set_conditional_codeobject();


#endif
